# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paraloger_GUI1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1314, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 1261, 661))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_project_tree = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_project_tree.setObjectName("label_project_tree")
        self.verticalLayout.addWidget(self.label_project_tree)
        self.treeWidget = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.treeWidget)
        self.label_object_details = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_object_details.setObjectName("label_object_details")
        self.verticalLayout.addWidget(self.label_object_details)
        self.tableView = QtWidgets.QTableView(self.horizontalLayoutWidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(3, 3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.main_tabWidget = QtWidgets.QTabWidget(self.horizontalLayoutWidget)
        self.main_tabWidget.setObjectName("main_tabWidget")
        self.tab_graph = QtWidgets.QWidget()
        self.tab_graph.setObjectName("tab_graph")
        self.main_tabWidget.addTab(self.tab_graph, "")
        self.tab_table = QtWidgets.QWidget()
        self.tab_table.setObjectName("tab_table")
        self.main_tabWidget.addTab(self.tab_table, "")
        self.tab_3d = QtWidgets.QWidget()
        self.tab_3d.setObjectName("tab_3d")
        self.main_tabWidget.addTab(self.tab_3d, "")
        self.horizontalLayout.addWidget(self.main_tabWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1314, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionimport = QtWidgets.QAction(MainWindow)
        self.actionimport.setObjectName("actionimport")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionimport)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionVersion)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_project_tree.setText(_translate("MainWindow", "Tree"))
        self.label_object_details.setText(_translate("MainWindow", "Details:"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.tab_graph), _translate("MainWindow", "Graph"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.tab_table), _translate("MainWindow", "Table"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.tab_3d), _translate("MainWindow", "3D"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuAbout.setTitle(_translate("MainWindow", "Abo&ut"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionimport.setText(_translate("MainWindow", "&import"))
        self.actionHelp.setText(_translate("MainWindow", "&Help"))
        self.actionVersion.setText(_translate("MainWindow", "&Version"))
        self.actionSave_as.setText(_translate("MainWindow", "&Save_as"))

